preload = /home/akreuzer/Pictures/Wallpapers/japanAtNight.jpg
wallpaper = eDP-1,/home/akreuzer/Pictures/Wallpapers/japanAtNight.jpg
wallpaper = DP-7,/home/akreuzer/Pictures/Wallpapers/japanAtNight.jpg
wallpaper = DP-9,/home/akreuzer/Pictures/Wallpapers/japanAtNight.jpg
ipc = off
