#!/usr/bin/env bash
set -e

if [ -z "$1" ]; then
  echo "Not updating flake.lock"
else
  nix flake update
fi

nixos-rebuild build --flake .
nvd diff /run/current-system ./result

echo
read -p "Switch[Ss]/Boot[Bb] " -r
if [[ $REPLY =~ ^[Ss] ]]; then
  doas ./result/bin/switch-to-configuration switch
elif [[ $REPLY =~ ^[Bb] ]]; then
  doas ./result/bin/switch-to-configuration boot
else
  echo "Cancelled"
fi
